# fly.toml app configuration file generated for donation-server on 2023-05-30T22:28:27+02:00
# fly launch --local-only --vm-cpukind shared --vm-cpus 1 --vm-memory 256
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "donation-server"
primary_region = "waw"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
  dockerfile = "Dockerfile"

[env]
  DONATION_SERVER_PORT = "8080"
  DONATION_SERVER_CUSTOMERS_TOPIC = "customers"
